### ISSUE TITLE
Maintenership hand-over

### ISSUE THREAD

**Issue by ocramz** [qnikst/binary-conduit#15]
Hi! I saw on Cafe that binary-conduit is up for grabs. I am a heavy user of conduit in general and I've started using this today. Happy to help out !

**Comment by qnikst** [comment]
Hi @ocramz! Thanks for your help, I've added you as a collaborator, and if you ok with that I transfer repository to your account.

**Comment by ocramz** [comment]
Sure, happy to take over !

**Comment by qnikst** [comment]
Great, I've sent a request!

**Comment by ocramz** [comment]
@qnikst sorry, it somehow expired. Could you send one again? Thanks!

**Comment by qnikst** [comment]
![image](https://user-images.githubusercontent.com/170227/103275120-7d5be180-49d4-11eb-8638-7761d1a4d35b.png)

It is marked as in the process of transfer for me

**Comment by qnikst** [comment]
I've sent one again, maybe it helps
